version: '2'

services:
  elasticsearch:
    image: elasticsearch:2.1.1
    command: elasticsearch -Des.network.host=_non_loopback_
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
  logstash:
    build: logstash/jmx-connector
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./logstash/logs:/etc/logstash/logs
    ports:
      - "5000:5000"
    links:
      - elasticsearch
  kibana:
    image: kibana:4.3
    volumes:
      - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    links:
      - elasticsearch
